// cli/templates/svelte/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  // Generated from the Zig `Commands` and `Events` (zig build types).
  import { invoke, listen, type Commands } from "./oriel";

  type AppInfo = Commands["app_info"]["result"];

  let name = $state("Oriel");
  let greeting = $state("");
  let count = $state(0);
  let info = $state<AppInfo | null>(null);
  let error = $state("");

  async function greet() {
    try {
      greeting = await invoke("greet", { name });
      error = "";
    } catch (err) {
      error = String(err);
    }
  }

  function submit(e: SubmitEvent) {
    e.preventDefault();
    greet();
  }

  onMount(() => {
    // Pushed from Zig by `events.emit(.greeted, ...)`.
    const off = listen("greeted", (e) => (count = e.count));
    greet();
    invoke("app_info").then((i) => (info = i));
    return off;
  });
</script>

<main>
  <h1>@@title@@</h1>
  <p class="tagline">Svelte + Vite, with Zig on the other side of invoke().</p>
  <form onsubmit={submit}>
    <input bind:value={name} placeholder="Your name" />
    <button type="submit">Greet</button>
  </form>
  <p class={error ? "greeting error" : "greeting"}>{error || greeting}</p>
  <p class="count">Greeted {count} {count === 1 ? "time" : "times"} (event from Zig)</p>
  {#if info}
    <footer>Zig {info.zig} · {info.mode}{info.dev ? " · dev server" : ""}</footer>
  {/if}
</main>

// examples/react/frontend/src/App.tsx
import { useEffect, useState, type FormEvent } from "react";
// Generated from the Zig `Commands` struct (zig build types / zig build dev).
import { invoke, listen, type Commands } from "./ziguri";

type Note = Commands["list_notes"]["result"][number];
type AppInfo = Commands["app_info"]["result"];

export function App() {
  const [info, setInfo] = useState<AppInfo | null>(null);
  const [notes, setNotes] = useState<Note[]>([]);
  const [draft, setDraft] = useState("");
  const [name, setName] = useState("Sergio");
  const [greeting, setGreeting] = useState("");
  const [error, setError] = useState("");
  const [dnd, setDnd] = useState(false);

  useEffect(() => {
    invoke("app_info").then(setInfo);
    invoke("list_notes").then(setNotes);
    invoke("do_not_disturb").then(setDnd);
    // Pushed from Zig, e.g. by the tray menu.
    const unlisten = [listen("notes_changed", setNotes), listen("do_not_disturb", setDnd)];
    return () => unlisten.forEach((off) => off());
  }, []);

  const run = async (action: () => Promise<void>) => {
    setError("");
    try {
      await action();
    } catch (e) {
      setError(String(e));
    }
  };

  const addNote = (e: FormEvent) => {
    e.preventDefault();
    run(async () => {
      setNotes(await invoke("add_note", { text: draft }));
      setDraft("");
    });
  };

  return (
    <main>
      <header>
        <h1>Notes</h1>
        {dnd && <span className="badge dnd">do not disturb</span>}
        {info && (
          <span className={`badge ${info.dev ? "dev" : "prod"}`}>
            {info.dev ? "dev · hot reload" : "production · embedded"} · Zig {info.zig} · {info.mode}
          </span>
        )}
      </header>

      <form onSubmit={addNote} className="row">
        <input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Write a note…" autoFocus />
        <button type="submit">Add</button>
      </form>
      {error && <p className="error">{error}</p>}

      <ul className="notes">
        {notes.map((note) => (
          <li key={note.id}>
            <span>{note.text}</span>
            <time>{note.created_at}</time>
            <button className="ghost" onClick={() => run(async () => setNotes(await invoke("delete_note", { id: note.id })))} aria-label="Delete note">
              ✕
            </button>
          </li>
        ))}
        {notes.length === 0 && <li className="empty">No notes yet: stored in SQLite, on the Zig side.</li>}
      </ul>

      <p className="hint">
        Close the window to keep notes in the tray. External links such as{" "}
        <a href="https://ziglang.org">ziglang.org</a> open in your browser.
      </p>

      <section className="row greet">
        <input value={name} onChange={(e) => setName(e.target.value)} />
        <button onClick={() => run(async () => setGreeting(await invoke("greet", { name })))}>Greet</button>
        <span>{greeting}</span>
      </section>
    </main>
  );
}
