// cli/templates/svelte/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  // Generated from the Zig `Commands` and `Events` (zig build types).
  import { invoke, listen, deepLink, type Commands } from "./oriel";

  type AppInfo = Commands["app_info"]["result"];

  let name = $state("Oriel");
  let greeting = $state("");
  let count = $state(0);
  let info = $state<AppInfo | null>(null);
  let error = $state("");
  let openedLink = $state<string | null>(null);

  async function greet() {
    try {
      greeting = await invoke("greet", { name });
      error = "";
    } catch (err) {
      error = String(err);
    }
  }

  function submit(e: SubmitEvent) {
    e.preventDefault();
    greet();
  }

  onMount(() => {
    // Pushed from Zig by `events.emit(.greeted, ...)`.
    const offGreeted = listen("greeted", (e) => (count = e.count));
    const offLink = listen("deep-link", (e) => (openedLink = e.url));
    deepLink?.current().then((url) => { if (url) openedLink = url; });
    greet();
    invoke("app_info").then((i) => (info = i));
    return () => {
      offGreeted();
      offLink();
    };
  });
</script>

<main>
  <h1>@@title@@</h1>
  <p class="tagline">Svelte + Vite, with Zig on the other side of invoke().</p>
  <form onsubmit={submit}>
    <input bind:value={name} placeholder="Your name" />
    <button type="submit">Greet</button>
  </form>
  <p class={error ? "greeting error" : "greeting"}>{error || greeting}</p>
  <p class="count">Greeted {count} {count === 1 ? "time" : "times"} (event from Zig)</p>
  {#if openedLink}
    <p class="opened-link">Opened via link: {openedLink}</p>
  {/if}
  {#if info}
    <footer>Zig {info.zig} · {info.mode}{info.dev ? " · dev server" : ""}</footer>
  {/if}
</main>

// cli/templates/vue/src/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
// Generated from the Zig `Commands` and `Events` (zig build types).
import { invoke, listen, deepLink, type Commands } from "./oriel";

type AppInfo = Commands["app_info"]["result"];

const name = ref("Oriel");
const greeting = ref("");
const count = ref(0);
const info = ref<AppInfo | null>(null);
const error = ref("");
const openedLink = ref<string | null>(null);

async function greet() {
  try {
    greeting.value = await invoke("greet", { name: name.value });
    error.value = "";
  } catch (err) {
    error.value = String(err);
  }
}

// Pushed from Zig by `events.emit(.greeted, ...)`.
const offGreeted = listen("greeted", (e) => (count.value = e.count));
const offLink = listen("deep-link", (e) => (openedLink.value = e.url));
onUnmounted(() => {
  offGreeted();
  offLink();
});

onMounted(async () => {
  deepLink?.current().then((url) => { if (url) openedLink.value = url; });
  greet();
  info.value = await invoke("app_info");
});
</script>

<template>
  <main>
    <h1>@@title@@</h1>
    <p class="tagline">Vue + Vite, with Zig on the other side of invoke().</p>
    <form @submit.prevent="greet">
      <input v-model="name" placeholder="Your name" />
      <button type="submit">Greet</button>
    </form>
    <p :class="error ? 'greeting error' : 'greeting'">{{ error || greeting }}</p>
    <p class="count">Greeted {{ count }} {{ count === 1 ? "time" : "times" }} (event from Zig)</p>
    <p v-if="openedLink" class="opened-link">Opened via link: {{ openedLink }}</p>
    <footer v-if="info">Zig {{ info.zig }} · {{ info.mode }}{{ info.dev ? " · dev server" : "" }}</footer>
  </main>
</template>
